# Generated by Django 3.0.6 on 2020-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('atalho', models.SlugField()),
                ('descricao', models.TextField(blank=True)),
                ('data_de_inicio', models.DateField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, upload_to='image')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
